[package]
name = "sshc"
description = "SSH Client to perform file copying and command execution"
authors = ["skitsanos, https://github.com/skitsanos"]

version = "0.2.0"
edition = "2021"

[dependencies]
ssh-rs = "0.3.3"
structopt = "0.3.26"
